config/routes.rb
Rails.application.routes.draw do
  root to: 'dogs#index'

  # get 'dogs/:id', to: 'dogs#show', as: :dog
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  BREEDS = File.readlines(Rails.root.join('config', 'breeds.txt')).map(&:strip)

  validates :name, :colour, presence: true
  validates :breed, inclusion: { in: BREEDS }

  def age
    Time.zone.now.year - birthdate.year
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update]

  def index
    @dogs = Dog.all
  end

  def show
  end

  def new
    @dog = Dog.new
  end

  def create
    # USE Strong Params
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to dogs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    # USE Strong Params
    if @dog.update(dog_params)
      redirect_to dogs_path
    else
      render :edit
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :colour, :breed, :birthdate)
  end

  def set_dog
    @dog = Dog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name %>

  <%= f.label :breed  %>
  <%= f.select :breed, collection: Dog::BREEDS %>

  <%= f.label :colour  %>
  <%= f.text_field :colour %>

  <%= f.label :birthdate  %>
  <%= f.text_field :birthdate %>

  <%= f.submit %>
<% end %>

app/views/dogs/index.html.erb
<h1>Dogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Breed</th>
    <th>Colour</th>
    <th>Age</th>
    <th>Actions</th>
  </tr>
  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.colour %></td>
        <td><%= pluralize(dog.age, 'year') %> old</td>
        <td>
          <%= link_to "Show", dog_path(dog) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add a Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>Add a Dog</h1>

<%= render 'form' %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instadogs269</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>